name: Build and Release

on:
  push:
    tags:
      - "v*"

env: 
  EXEC: demo
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag 
        id: version 
        run: | 
          VERSION="${GITHUB_REF#refs/tags/}" 
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config cmake ninja-build git

      - name: Build and install SDL3 from source 
        run: | 
          git clone https://github.com/libsdl-org/SDL.git 
          cd SDL 
          cmake -S . -B build -G Ninja -DSDL_STATIC=OFF -DSDL_SHARED=ON 
          cmake --build build 
          sudo cmake --install build

      - name: Build project
        run: make

      - name: Archive executable
        run: |
          mkdir -p dist
          cp ./${EXEC} dist/${EXEC}-${VERSION}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }} 
          name: Release ${{ env.VERSION }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
