name: Build and Release using Cmake

on:
  workflow_dispatch: 

permissions:
  contents: write

env: 
  EXEC: demo
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config cmake ninja-build git

      - name: Build and install SDL3 from source 
        run: |
          sudo apt-get install -y gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev
          git clone https://github.com/libsdl-org/SDL.git 
          cd SDL 
          cmake -S . -B build -G Ninja -DSDL_STATIC=OFF -DSDL_SHARED=ON 
          cmake --build build 
          sudo cmake --install build

      - name: Build Linux exec using Cmake
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Build Windows exec using Cmake
        run: |
          cmake -S . -B build -G "MinGW Makefiles"
          cmake --build build

      - name: Archive executable
        run: |
          mkdir -p dist
          cp ./${EXEC} dist/${EXEC}-${VERSION}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cmake
          name: Release cmake
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
